[theme]
primaryColor = "#DC3545"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6FA"
textColor = "#1E293B"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"

[server]
maxUploadSize = 200
runOnSave = true

[ui]
hideTopBar = false
hideSidebarNav = false
